spring.profiles.active=dev
server.port=8084

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto= create
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:/sql/sql.sql

token.signing.key=${JWT_SECRET:default-secret-key}