spring.profiles.active=dev
server.port=8084

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/

#spring.sql.init.mode=never
jwt.refresh.expiration=604800000 
token.signing.key=${JWT_SECRET:default-secret-key}

logging.level.com.epam.rd.autocode.spring.project=DEBUG

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile