spring.profiles.active=dev
server.port=8084

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/

#spring.sql.init.mode=never

token.signing.key=${JWT_SECRET:default-secret-key}

logging.level.com.epam.rd.autocode.spring.project=DEBUG