version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=YOUR_NAME_DB
      - POSTGRES_USER=YOUR_NAME_USER
      - POSTGRES_PASSWORD=YOUR_PASSWORD
    volumes:
      - db:/var/lib/postgresql/book_store
    ports:
      - "5435:5432"

volumes:
  db: